### ISSUE TITLE
Export to Cytoscape

### ISSUE THREAD

**Issue by GrigoriiAndrianov** [ctlab/gatom#4]
Hello. I try open network in Cytoscape (v. 3.5.1), but I receive error "Could not parse XGMML file" (in svg everything is fine).  

Could you give me some advice how solve the problem?

[M0.vs.M1.module.zip](https://github.com/ctlab/gatom/files/1447217/M0.vs.M1.module.zip)

**Comment by assaron** [comment]
Thanks for the report. For now you can just remove `reaction_equation` line:
```{bash}
grep -v reaction_equation M0.vs.M1.module.xgmml > M0.vs.M1.new.xgmml
```
